<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <ProduceReferenceAssemblyInOutDir>true</ProduceReferenceAssemblyInOutDir>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Fonts\VisionBold.ttf" />
    <None Remove="Fonts\VisionRegular.ttf" />
    <None Remove="Images\arrowDown.png" />
    <None Remove="Images\arrowUp.png" />
    <None Remove="Images\bg.jpg" />
    <None Remove="Images\bg1.jpg" />
    <None Remove="Images\calendar.png" />
    <None Remove="Images\checkcircle.png" />
    <None Remove="Images\clock.png" />
    <None Remove="Images\pause.png" />
    <None Remove="Images\play.png" />
    <None Remove="Images\pluscircle.png" />
    <None Remove="Images\refreshccw.png" />
    <None Remove="Images\rotateccw.png" />
    <None Remove="Images\trash.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Fonts\VisionBold.ttf" />
    <EmbeddedResource Include="Fonts\VisionRegular.ttf" />
    <EmbeddedResource Include="Images\arrowDown.png" />
    <EmbeddedResource Include="Images\arrowUp.png" />
    <EmbeddedResource Include="Images\bg.jpg" />
    <EmbeddedResource Include="Images\bg1.jpg" />
    <EmbeddedResource Include="Images\calendar.png" />
    <EmbeddedResource Include="Images\checkcircle.png" />
    <EmbeddedResource Include="Images\clock.png" />
    <EmbeddedResource Include="Images\pause.png" />
    <EmbeddedResource Include="Images\play.png" />
    <EmbeddedResource Include="Images\pluscircle.png" />
    <EmbeddedResource Include="Images\refreshccw.png" />
    <EmbeddedResource Include="Images\rotateccw.png" />
    <EmbeddedResource Include="Images\trash.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
    <PackageReference Include="Xam.Plugin.SimpleAudioPlayer" Version="1.6.0" />
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2196" />
    <PackageReference Include="Xamarin.Essentials" Version="1.7.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="FreeTimerFlyout.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="HobbyEditor.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Page1.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Purposes.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Shedule.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="TimerPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
  </ItemGroup>
</Project>